### ISSUE TITLE
Some users expect MIT to appear earlier than MIT-*

### ISSUE THREAD

**Issue by jeffmcaffer** [jslicense/spdx-license-ids#10]
in https://github.com/shinnn/spdx-license-ids/blob/master/index.json the license ids appear to be sorted alphabetically however the `MIT` entry is not first in the `MIT*` family of ids. It would just be handy if they were already sorted.

**Comment by shinnn** [comment]
This library just uses the data fetched from https://spdx.org/licenses/licenses.json and we don't sort results by ourselves. If you have any complaints against the order of the original license list, [ask SPDX Workgroup about it](https://github.com/spdx/license-list-data/issues/new) instead.

**Comment by shinnn** [comment]
https://github.com/clearlydefined/website/issues/299#issuecomment-442555789

> Now, the SPDX list is updated

No.

**Comment by kemitchell** [comment]
Strongly recommend that code using this module do its own `.sort()` if it needs predictable order.

https://github.com/clearlydefined/website/issues/299#issuecomment-442561637

**Comment by shinnn** [comment]
What I mean is, https://github.com/spdx/license-list-data/ is actually updated, congraturations. But https://spdx.org/licenses/ is not.

**Comment by shinnn** [comment]
@kemitchell Do you really think so though https://github.com/spdx/tools/commit/7c4a67fba02d3a220c71101845c206121fc3e9f1 is introduced.

**Comment by kemitchell** [comment]
@shinnn I wouldn't make the sorting behavior of a website part of the API of the `spdx-license-ids` package. Sorting costs very little in performance. Even if performance is a concern, users can always sort in a build step, before runtime.

**Comment by kemitchell** [comment]
@shinnn If you really want sorted data, I suggest you do it in _your_ build step. Sort in `build.js`, in some deterministic, platform-independent way. Publish that sorted data file to npm.

**Comment by shinnn** [comment]
> If you really want sorted data

[I don't.](https://github.com/shinnn/spdx-license-ids/issues/10#issuecomment-420140759)

**Comment by kemitchell** [comment]
@shinnn I think that's fine. Let downstream users sort or otherwise post-process if they need to.
