### ISSUE TITLE
Get NONE and NOASSERTION options added 

### ISSUE THREAD

**Issue by moranthomas** [jslicense/spdx-license-ids#11]
In the project https://github.com/clearlydefined we currently only have a notion of a component missing a license. However, there are components that are not missing licenses, they in fact have no license. We want to implement a way to support that and display it to the user. These options from the licence picker (on our side) are coming directly from here and so the ask is: 
Can we please get these 2 options (NONE and NOASSERTION) added ?

**Comment by kemitchell** [comment]
@moranthomas The IDs in this package are provided by a standard, SPDX. That standard is actually much broader than the list of IDs, and includes options for missing license information, but they won't be much good for your license picker.

I'd strongly recommend that you add your `NONE` and `NOASSERTION` options in your app. They aren't part of the spec, and don't belong in this package. It could be as simple as `require('spdx-license-ids').concat('NONE', 'NOASSERT')`.
