### ISSUE TITLE
Add `spdx-license-ids/fsf` and `spdx-license-ids/osi`

### ISSUE THREAD

**Issue by bnb** [jslicense/spdx-license-ids#16]
There is some additional metadata contained within the SPDX License list: FSF Free/Libre and OSI Approved.

As a user building something around spdx-license-ids, it would be stellar if these were additional exports from the module that followed a similar model to `spdx-license-ids/deprecated`:

```js
const freeSoftwareLicenses = require('spdx-license-ids/fsf')
const osiApprovedLicenses = require('spdx-license-ids/osi')
```

If this is something you're interested in, I'd be happy to try to contribute it @shinnn ❤️

**Comment by bnb** [comment]
Additionally, there could possibly be an `spdx-license-ids/fsf-and-osi` that is the set of licenses that are _both_ FSF Free/Libre and OSI approved.

**Comment by kemitchell** [comment]
https://www.npmjs.com/package/spdx-osi

**Comment by bnb** [comment]
@kemitchell do you know of one for FSF as well? 🤔

(also thank you for all the license work you do, using several of your modules already)

**Comment by kemitchell** [comment]
@bnb, I do not.  If you wanted to try, you'd probably start with <https://www.gnu.org/licenses/license-list.en.html>.  I'd be happy to host that package under https://github.com/jslicense and invite you to the org.

Of potential interest: https://www.npmjs.com/package/@blueoak/list

I strongly suspect that Blue Oak Council will package a data package on copyleft terms, as well.

**Comment by bnb** [comment]
very sad to see this closed, as I genuinely believe it would be useful and it makes sense to have information provided by SPDX exposed by what is effectively the de facto SPDX license id module.
