### ISSUE TITLE
TypeScript types for spdx-license-list

### ISSUE THREAD

**Issue by ddgenome** [jslicense/spdx-license-ids#20]
I have created a set of types for spdx-license-list. Would you prefer I add them to this repository via a PR or create a `@types/spdx-license-list` package via [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by kemitchell** [comment]
@shinnn, I would personally prefer to keep this repo as simple as possible.

**Comment by ddgenome** [comment]
Understood.

**Comment by shellscape** [comment]
@kemitchell considering the types for this are all of 4 lines, that's a pretty weak argument. For anyone happening by that needs types for this, and would prefer not to deal with `any`, here you are:

```typescript
declare module 'spdx-license-ids*' {
  const Licenses: string[];

  export = Licenses;
}
```

**Comment by JamieMagee** [comment]
You can now use [`@types/spdx-license-ids`](https://www.npmjs.com/package/@types/spdx-license-ids)
