### ISSUE TITLE
Should `main` contain ac5d871e4c1aa830b67e7066ad91100300afa61e?

### ISSUE THREAD

**Issue by neverendingqs** [jslicense/spdx-license-ids#28]
`main` currently shows that this package is at `v3.0.10`: https://github.com/jslicense/spdx-license-ids/blob/9d262560a6bffdf1154c858e90faad2a09d1f78b/package.json#L3

Should ac5d871e4c1aa830b67e7066ad91100300afa61e from the [`v3.0.10`](https://github.com/jslicense/spdx-license-ids/commits/v3.0.10/package.json) tag be in `main` as well?

**Comment by kemitchell** [comment]
Fast-forwarded.
