### ISSUE TITLE
Node module compatibility

### ISSUE THREAD

**Issue by clementbiron** [jslicense/spdx-license-ids#30]
Hello 🔆 

It would be great if `spdx-license-ids` becomes compatible with Node module, e.g:

```javascript
import ids from 'spdx-license-ids';
```

 For now, [import assertions](https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#import-assertions) are experimental and not recommended in production environments.

**Comment by kemitchell** [comment]
The deployment form of this package is just a single JSON file.

If/when npm and the broader ecosystem offer a concrete, compatible way to tell the new module system that's what's going on, I'll be happy to take a PR.
