### ISSUE TITLE
The `spdx-license-list` module now includes a `Set` of license IDs

### ISSUE THREAD

**Issue by sindresorhus** [jslicense/spdx-license-ids#7]
You could use it here or deprecate this module in favor of it.

See: https://github.com/sindresorhus/spdx-license-list/releases/tag/v3.0.0

**Comment by shinnn** [comment]
Thanks for the suggestion.

> deprecate this module in favor of it.

No. This module is still useful for the people who prefer the more loosely licensed ones. (`spdx-license-ids` is licensed under `CC0-1.0` but `spdx-license-list` is  `MIT` and you claims its copyright.)

> could use it here

In JSON build step, or in the main script such as `module.exports = Array.from(require('spdx-license-list/simple'));` ?

**Comment by sindresorhus** [comment]
> but spdx-license-list is MIT and you claims its copyright.)

Good point. Fixed: https://github.com/sindresorhus/spdx-license-list/commit/16d0a9fbbdfd6370b412c16392dbd35c26a689b0 v3.0.1

> In JSON build step, or in the main script such as module.exports = Array.from(require('spdx-license-list/simple')); ?

No longer any need to have a build script. Converting between Array and Map once for such a small list is performance negligible.

**Comment by shinnn** [comment]
Cool. Happy to see [a lot of improvements in your project](https://github.com/sindresorhus/spdx-license-list/releases/tag/v3.0.0). But, I still like this repository as it is.

If this project depends on yours, I need to wait for the update of `spdx-license-list` whenever I update the list included in `spdx-license-ids`. This module has been more actively maintained by me and @kemitchell (one of the spdx.org members) and I don't feel the need to change the current development environment.

I'm sorry to turn down your proposal.
